### ISSUE TITLE
not work on heroku :(

### ISSUE THREAD

**Issue by todokku** [sayem314/torrent-indexer#1]
Hi Sayem,
I deployed this repo on heroku & after completed deploy run :
yarn add torrent-indexer
but after open app recived "Application error"
please tell me which version of yarn & npm using in this project 
& if its possible make it friendly to easy deploy on heroku 
waiting for your response
finest regards
goodbye

**Comment by sayem314** [comment]
This is not meant to be used for indexing directly but rather programmatically, you will have to write your own program and use indexer api as per example. Please see this [example application](https://github.com/sayem314/torrenter).
